version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: OpenSSL 1.0.x (Linux)
          command: python3 setup.py test
      - run:
          name: OpenSSL 1.1.x (Linux)
          command: python3 setup.py test --openssl-1-1
